[package]
name = "pkl-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.1.2"
rmpv = "1.0.1"
serde = { version = "1.0", features = ["derive"] }

# Gated dependencies
convert_case = { version = "0.6.0", optional = true }
dhat = { version = "0.3.3", optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-subscriber = { version = "0.3.18", optional = true }

[dev-dependencies]
serde_json = "1.0.117"


[features]
default = []
trace = ["tracing", "tracing-subscriber"]
dhat-heap = ["dhat"]    # if you are doing heap profiling
dhat-ad-hoc = ["dhat"]  # if you are doing ad hoc profiling
codegen = ["convert_case"]  # if you are doing ad hoc profiling

[profile.release]
debug = 1
